#!/usr/bin/env python3
"""Write source/test/SunWindowGlanceAreas.mc: the glance content area of every product in the manifest, by screen size.

Usage: python3 tools/gen_glance_areas.py      (reads the SDK's Devices/<id>/simulator.json "glance.contentArea")
The glance fit test draws the widest glance states into a bitmap of each area that belongs to the running product's screen
size (width and height), with that product's own fonts. The areas are the simulator's; a wrist has not confirmed them
(docs/compatibility.md). Run it again when the manifest changes.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DEVICES = os.path.expanduser("~/Library/Application Support/Garmin/ConnectIQ/Devices")
MANIFEST = os.path.join(HERE, "..", "manifest.xml")
OUT = os.path.join(HERE, "..", "source", "test", "SunWindowGlanceAreas.mc")

ids = re.findall(r'<iq:product id="([^"]+)"', open(MANIFEST).read())
rows = {}
for d in ids:
    res = json.load(open(os.path.join(DEVICES, d, "compiler.json")))["resolution"]
    area = json.load(open(os.path.join(DEVICES, d, "simulator.json")))["glance"]["contentArea"]
    rows.setdefault((res["width"], res["height"], area["width"], area["height"]), []).append(d)
body = ",\n        ".join(f"[{a}, {b}, {c}, {e}]" for (a, b, c, e) in sorted(rows))
src = f'''import Toybox.Lang;
import Toybox.Test;

// GENERATED by tools/gen_glance_areas.py from the SDK's compiler.json and simulator.json files. Do not edit by hand.
// {len(rows)} distinct (screen, glance area) pairs over {len(ids)} products: [screen width, screen height, glance width, glance height] in px.
(:test)
class SunWindowGlanceAreas {{
    static const ALL = [
        {body}
    ] as Array<Array<Number>>;
}}
'''
open(OUT, "w").write(src)
print("wrote", os.path.normpath(OUT), len(rows), "pairs")
for k, devs in sorted(rows.items()):
    print(k, len(devs), "products", devs[:3])
