#!/usr/bin/env python3
"""Write source/test/SunWindowSunReferenceTest.mc from the research fixtures (NOAA formulas, JPL Horizons agrees to 0.0061 deg).

Usage: python3 tools/gen_sun_tests.py          (stdlib only, no network: the Horizons parts of the fixtures are not called)
The reference is research_notes/Vitamin D window/solar_elevation_fixtures.py: elev_noaa (elevation at an instant) and
day_model + first_last_min (the 45-degree window as whole minutes: first = ceil, last = floor). Tolerances (spec.md D9):
0.02 degrees on elevation, 1 minute on a window edge. Dates are 2026 only; never assert an exact edge DATE of the year
(a knife-edge day can differ by one), only counts within 2 days.
"""
import datetime as dt
import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "..", "..", "research_notes", "Vitamin D window", "solar_elevation_fixtures.py")
OUT = os.path.join(HERE, "..", "source", "test", "SunWindowSunReferenceTest.mc")

spec = importlib.util.spec_from_file_location("fixtures", FIX)
fx = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fx)

EPOCH = dt.date(1970, 1, 1)


def day_number(d):
    return (d - EPOCH).days


# Places the fixtures do not have: UTC+13 and +14 west of the date line, where local solar noon is a day late unless wrapped
# (the code review of 2026-10-10 found it). No daylight saving there in 2026. name: (lat N+, lon E+, offset hours).
EXTRA = {"Apia": (-13.833, -171.75, 13), "Kiritimati": (1.87, -157.4, 14)}


def window_rows():
    """[lat, lon, local day number, offset minutes, open, close] with open = -1 for 'none' (local minutes of day)."""
    rows = []
    places = [(p, lat, lon, None) for p, (lat, lon, std) in fx.PLACES.items()]
    places += [(p, lat, lon, o) for p, (lat, lon, o) in EXTRA.items()]
    for p, lat, lon, fixed in places:
        for d in fx.DATES:
            o = fixed if fixed is not None else fx.off(p, d)
            m = fx.day_model(lat, lon, d, o)
            c = m[45]
            if c is None:
                rows.append((p, lat, lon, day_number(d), o * 60, -1, -1))
            else:
                a, b = fx.first_last_min(c)
                rows.append((p, lat, lon, day_number(d), o * 60, a + o * 60, b + o * 60))
    return rows


def elevation_rows():
    """[lat, lon, UTC day number, UTC minute, elevation]: local hours 6, 9, 12, 15, 18 at each place and date."""
    rows = []
    for p, (lat, lon, std) in fx.PLACES.items():
        for d in fx.DATES:
            o = fx.off(p, d)
            for h in (6, 9, 12, 15, 18):
                minutes = h * 60 - o * 60
                rows.append((p, lat, lon, day_number(d), minutes, fx.elev_noaa(lat, lon, d, minutes)))
    return rows


def year_counts():
    """Days of 2026 whose local day reaches 45 degrees, per place (standard offset, as the fixtures' year scan)."""
    out = []
    days = [dt.date(2026, 1, 1) + dt.timedelta(days=i) for i in range(365)]
    for p, (lat, lon, std) in fx.PLACES.items():
        n = sum(1 for d in days if fx.day_model(lat, lon, d, std)[45] is not None)
        out.append((p, lat, lon, std * 60, n))
    return out


def arr(rows, fmt):
    return ",\n        ".join(fmt(r) for r in rows)


def main():
    w, e, y = window_rows(), elevation_rows(), year_counts()
    src = f'''import Toybox.Lang;
import Toybox.Test;

// GENERATED by tools/gen_sun_tests.py from research_notes/Vitamin D window/solar_elevation_fixtures.py. Do not edit by hand.
// The reference is the NOAA formulas in Python (JPL Horizons agrees to 0.0061 degrees, 2026 only). Tolerances: 0.02 degrees
// on elevation and 1 minute on a window edge (docs/spec.md D9). Simulator only: a wrist check (D9) compares the owner's place.
(:test)
class SunWindowSunReference {{
    // [latitude, longitude, local day number, offset minutes, open, close] in local minutes of the day; -1 = none today.
    static const WINDOWS = [
        {arr(w, lambda r: f"[{r[1]}d, {r[2]}d, {r[3]}, {r[4]}, {r[5]}, {r[6]}]")}
    ] as Array<Array<Number or Double>>;
    // [latitude, longitude, UTC day number, UTC minute, elevation degrees].
    static const ELEVATIONS = [
        {arr(e, lambda r: f"[{r[1]}d, {r[2]}d, {r[3]}, {r[4]}, {r[5]:.5f}d]")}
    ] as Array<Array<Number or Double>>;
    // [latitude, longitude, standard offset minutes, days of 2026 that reach the line].
    static const YEAR_DAYS = [
        {arr(y, lambda r: f"[{r[1]}d, {r[2]}d, {r[3]}, {r[4]}]")}
    ] as Array<Array<Number or Double>>;
}}

// Every place and date of the fixtures: the window (or its absence) and both edges within a minute.
(:test)
function windowEdgesMatchTheFixtures(logger as Test.Logger) as Boolean {{
    var rows = SunWindowSunReference.WINDOWS;
    for (var i = 0; i < rows.size(); i++) {{
        var r = rows[i];
        var day = SunWindowSun.day(r[2] as Number, r[0] as Double, r[1] as Double, r[3] as Number);
        var open = r[4] as Number;
        var close = r[5] as Number;
        Test.assertMessage(day.hasWindow == (open >= 0), "row " + i + " window presence");
        if (open >= 0) {{
            Test.assertMessage((day.open - open).abs() <= 1, "row " + i + " open " + day.open + " vs " + open);
            Test.assertMessage((day.close - close).abs() <= 1, "row " + i + " close " + day.close + " vs " + close);
        }}
    }}
    return true;
}}

// The elevation pipeline (parameters at the instant, then the hour angle) within 0.02 degrees.
(:test)
function elevationMatchesTheFixtures(logger as Test.Logger) as Boolean {{
    var rows = SunWindowSunReference.ELEVATIONS;
    for (var i = 0; i < rows.size(); i++) {{
        var r = rows[i];
        var got = SunWindowSun.elevationAtUtc(r[0] as Double, r[1] as Double, r[2] as Number, (r[3] as Number).toDouble());
        var want = r[4] as Double;
        Test.assertMessage((got - want).abs() <= 0.02d, "row " + i + " elevation " + got + " vs " + want);
    }}
    return true;
}}

// How many days of 2026 reach 45 degrees at each place, within 2 days of the fixtures' year scan (a knife-edge day can differ).
(:test)
function yearCountsMatchTheFixtures(logger as Test.Logger) as Boolean {{
    var rows = SunWindowSunReference.YEAR_DAYS;
    var first = SunWindowCalendar.dayNumber(2026, 1, 1);
    for (var i = 0; i < rows.size(); i++) {{
        var r = rows[i];
        var count = 0;
        for (var d = 0; d < 365; d++) {{
            if (SunWindowSun.day(first + d, r[0] as Double, r[1] as Double, r[2] as Number).hasWindow) {{
                count += 1;
            }}
        }}
        Test.assertMessage((count - (r[3] as Number)).abs() <= 2, "row " + i + " days " + count + " vs " + r[3]);
    }}
    return true;
}}
'''
    with open(OUT, "w") as f:
        f.write(src)
    print("wrote", os.path.normpath(OUT), len(w), "windows,", len(e), "elevations,", len(y), "places")
    for r in y:
        print(r[0], r[4], "days")


main()
