import Toybox.Lang;
import Toybox.Test;

// GENERATED by tools/gen_sun_tests.py from reference_sun_times.tsv (US Naval Observatory). Do not edit by hand.
// Every value is local minutes since local midnight; tolerance is 2 minutes (a sunset after midnight is +1440).

function sunAssertNear(actual as Number or Null, expected as Number, label as String) as Void {
    Test.assert(actual != null);
    Test.assertMessage((actual as Number) - expected <= 2 && expected - (actual as Number) <= 2, label + " " + actual + " vs " + expected);
}

function sunAssertNoonNear(actual as Number, expected as Number, label as String) as Void {
    // Solar noon is compared around the clock (a noon just after midnight would be 1440 + n).
    var diff = (actual - expected) % TwoSunsConfig.MINUTES_PER_DAY;
    if (diff < 0) {
        diff += TwoSunsConfig.MINUTES_PER_DAY;
    }
    Test.assertMessage(diff <= 2 || diff >= TwoSunsConfig.MINUTES_PER_DAY - 2, label + " noon " + actual + " vs " + expected);
}

(:test)
function sunReferenceLondonBst(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, 51.5, -0.12, 60);
    sunAssertNoonNear(sun.noon, 771, "London BST");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 415, "London BST rise");
    sunAssertNear(sun.set, 1127, "London BST set");
    sunAssertNear(sun.civilBegin, 381, "London BST civilBegin");
    sunAssertNear(sun.civilEnd, 1161, "London BST civilEnd");
    return true;
}

(:test)
function sunReferenceLondonGmt(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, 51.5, -0.12, 0);
    sunAssertNoonNear(sun.noon, 719, "London GMT");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 484, "London GMT rise");
    sunAssertNear(sun.set, 953, "London GMT set");
    sunAssertNear(sun.civilBegin, 443, "London GMT civilBegin");
    sunAssertNear(sun.civilEnd, 994, "London GMT civilEnd");
    return true;
}

(:test)
function sunReferenceLondonBstSolstice(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 6, 21, 51.5, -0.12, 60);
    sunAssertNoonNear(sun.noon, 782, "London BST solstice");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 283, "London BST solstice rise");
    sunAssertNear(sun.set, 1281, "London BST solstice set");
    sunAssertNear(sun.civilBegin, 235, "London BST solstice civilBegin");
    sunAssertNear(sun.civilEnd, 1329, "London BST solstice civilEnd");
    return true;
}

(:test)
function sunReferenceLondonDstStartDay(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 3, 29, 51.5, -0.12, 60);
    sunAssertNoonNear(sun.noon, 785, "London DST start day");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 403, "London DST start day rise");
    sunAssertNear(sun.set, 1169, "London DST start day set");
    sunAssertNear(sun.civilBegin, 369, "London DST start day civilBegin");
    sunAssertNear(sun.civilEnd, 1202, "London DST start day civilEnd");
    return true;
}

(:test)
function sunReferenceLondonDstEndDay(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 10, 25, 51.5, -0.12, 0);
    sunAssertNoonNear(sun.noon, 705, "London DST end day");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 402, "London DST end day rise");
    sunAssertNear(sun.set, 1007, "London DST end day set");
    sunAssertNear(sun.civilBegin, 367, "London DST end day civilBegin");
    sunAssertNear(sun.civilEnd, 1041, "London DST end day civilEnd");
    return true;
}

(:test)
function sunReferenceDubaiUtc4(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, 25.2, 55.27, 240);
    sunAssertNoonNear(sun.noon, 730, "Dubai UTC+4");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 369, "Dubai UTC+4 rise");
    sunAssertNear(sun.set, 1090, "Dubai UTC+4 set");
    sunAssertNear(sun.civilBegin, 347, "Dubai UTC+4 civilBegin");
    sunAssertNear(sun.civilEnd, 1113, "Dubai UTC+4 civilEnd");
    return true;
}

(:test)
function sunReferenceDubaiUtc4Winter(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, 25.2, 55.27, 240);
    sunAssertNoonNear(sun.noon, 737, "Dubai UTC+4 winter");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 420, "Dubai UTC+4 winter rise");
    sunAssertNear(sun.set, 1054, "Dubai UTC+4 winter set");
    sunAssertNear(sun.civilBegin, 395, "Dubai UTC+4 winter civilBegin");
    sunAssertNear(sun.civilEnd, 1079, "Dubai UTC+4 winter civilEnd");
    return true;
}

(:test)
function sunReferenceHonoluluUtc10NoDst(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, 21.3, -157.86, -600);
    sunAssertNoonNear(sun.noon, 742, "Honolulu UTC-10 no DST");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 382, "Honolulu UTC-10 no DST rise");
    sunAssertNear(sun.set, 1103, "Honolulu UTC-10 no DST set");
    sunAssertNear(sun.civilBegin, 359, "Honolulu UTC-10 no DST civilBegin");
    sunAssertNear(sun.civilEnd, 1125, "Honolulu UTC-10 no DST civilEnd");
    return true;
}

(:test)
function sunReferenceHonoluluJune(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 6, 21, 21.3, -157.86, -600);
    sunAssertNoonNear(sun.noon, 753, "Honolulu June");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 350, "Honolulu June rise");
    sunAssertNear(sun.set, 1156, "Honolulu June set");
    sunAssertNear(sun.civilBegin, 326, "Honolulu June civilBegin");
    sunAssertNear(sun.civilEnd, 1181, "Honolulu June civilEnd");
    return true;
}

(:test)
function sunReferenceSydneyAest(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, -33.87, 151.2, 600);
    sunAssertNoonNear(sun.noon, 706, "Sydney AEST");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 338, "Sydney AEST rise");
    sunAssertNear(sun.set, 1075, "Sydney AEST set");
    sunAssertNear(sun.civilBegin, 313, "Sydney AEST civilBegin");
    sunAssertNear(sun.civilEnd, 1100, "Sydney AEST civilEnd");
    return true;
}

(:test)
function sunReferenceSydneyAedt(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, -33.87, 151.2, 660);
    sunAssertNoonNear(sun.noon, 773, "Sydney AEDT");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 341, "Sydney AEDT rise");
    sunAssertNear(sun.set, 1205, "Sydney AEDT set");
    sunAssertNear(sun.civilBegin, 311, "Sydney AEDT civilBegin");
    sunAssertNear(sun.civilEnd, 1235, "Sydney AEDT civilEnd");
    return true;
}

(:test)
function sunReferenceKathmanduUtc545(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, 27.7, 85.32, 345);
    sunAssertNoonNear(sun.noon, 715, "Kathmandu UTC+5:45");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 354, "Kathmandu UTC+5:45 rise");
    sunAssertNear(sun.set, 1075, "Kathmandu UTC+5:45 set");
    sunAssertNear(sun.civilBegin, 331, "Kathmandu UTC+5:45 civilBegin");
    sunAssertNear(sun.civilEnd, 1098, "Kathmandu UTC+5:45 civilEnd");
    return true;
}

(:test)
function sunReferenceAucklandNzst(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 6, 21, -36.85, 174.76, 720);
    sunAssertNoonNear(sun.noon, 743, "Auckland NZST");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 454, "Auckland NZST rise");
    sunAssertNear(sun.set, 1032, "Auckland NZST set");
    sunAssertNear(sun.civilBegin, 425, "Auckland NZST civilBegin");
    sunAssertNear(sun.civilEnd, 1061, "Auckland NZST civilEnd");
    return true;
}

(:test)
function sunReferenceNewYorkEdt(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 27, 40.71, -74.0, -240);
    sunAssertNoonNear(sun.noon, 767, "New York EDT");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 409, "New York EDT rise");
    sunAssertNear(sun.set, 1125, "New York EDT set");
    sunAssertNear(sun.civilBegin, 381, "New York EDT civilBegin");
    sunAssertNear(sun.civilEnd, 1152, "New York EDT civilEnd");
    return true;
}

(:test)
function sunReferenceNewYorkDstStartDay(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 3, 8, 40.71, -74.0, -240);
    sunAssertNoonNear(sun.noon, 787, "New York DST start day");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 439, "New York DST start day rise");
    sunAssertNear(sun.set, 1135, "New York DST start day set");
    sunAssertNear(sun.civilBegin, 412, "New York DST start day civilBegin");
    sunAssertNear(sun.civilEnd, 1162, "New York DST start day civilEnd");
    return true;
}

(:test)
function sunReferenceDenverMst(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, 39.74, -104.99, -420);
    sunAssertNoonNear(sun.noon, 718, "Denver MST");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 438, "Denver MST rise");
    sunAssertNear(sun.set, 999, "Denver MST set");
    sunAssertNear(sun.civilBegin, 407, "Denver MST civilBegin");
    sunAssertNear(sun.civilEnd, 1029, "Denver MST civilEnd");
    return true;
}

(:test)
function sunReferenceReykjavikUtc0(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 6, 21, 64.15, -21.94, 0);
    sunAssertNoonNear(sun.noon, 810, "Reykjavik UTC+0");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 175, "Reykjavik UTC+0 rise");
    sunAssertNear(sun.set, 1444, "Reykjavik UTC+0 set");
    Test.assert(sun.civilBegin == null);
    Test.assert(sun.civilEnd == null);
    return true;
}

(:test)
function sunReferenceReykjavikWinter(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, 64.15, -21.94, 0);
    sunAssertNoonNear(sun.noon, 806, "Reykjavik winter");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 682, "Reykjavik winter rise");
    sunAssertNear(sun.set, 929, "Reykjavik winter set");
    sunAssertNear(sun.civilBegin, 603, "Reykjavik winter civilBegin");
    sunAssertNear(sun.civilEnd, 1009, "Reykjavik winter civilEnd");
    return true;
}

(:test)
function sunReferenceTromsoPolarNight(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, 69.6496, 18.956, 60);
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_DOWN_ALL_DAY);
    Test.assert(sun.rise == null && sun.set == null);
    sunAssertNear(sun.civilBegin, 571, "Tromso polar night civilBegin");
    sunAssertNear(sun.civilEnd, 833, "Tromso polar night civilEnd");
    return true;
}

(:test)
function sunReferenceTromsoMidnightSun(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 6, 21, 69.6496, 18.956, 120);
    sunAssertNoonNear(sun.noon, 766, "Tromso midnight sun");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_UP_ALL_DAY);
    Test.assert(sun.rise == null && sun.set == null);
    Test.assert(sun.civilBegin == null);
    Test.assert(sun.civilEnd == null);
    return true;
}

(:test)
function sunReferenceTromsoSunReturns(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2027, 1, 21, 69.6496, 18.956, 60);
    sunAssertNoonNear(sun.noon, 715, "Tromso sun returns");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 630, "Tromso sun returns rise");
    sunAssertNear(sun.set, 801, "Tromso sun returns set");
    sunAssertNear(sun.civilBegin, 520, "Tromso sun returns civilBegin");
    sunAssertNear(sun.civilEnd, 912, "Tromso sun returns civilEnd");
    return true;
}

(:test)
function sunReferenceTromsoSunReturns1(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2027, 1, 20, 69.6496, 18.956, 60);
    sunAssertNoonNear(sun.noon, 715, "Tromso sun returns -1");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 638, "Tromso sun returns -1 rise");
    sunAssertNear(sun.set, 793, "Tromso sun returns -1 set");
    sunAssertNear(sun.civilBegin, 523, "Tromso sun returns -1 civilBegin");
    sunAssertNear(sun.civilEnd, 908, "Tromso sun returns -1 civilEnd");
    return true;
}

(:test)
function sunReferenceTromsoMidnightSunStarts(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 5, 18, 69.6496, 18.956, 120);
    sunAssertNoonNear(sun.noon, 761, "Tromso midnight sun starts");
    // Transition day: USNO lists events one noon-declination says do not exist; nothing stricter than noon.
    return true;
}

(:test)
function sunReferenceTromsoMidnightSunStarts1(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 5, 19, 69.6496, 18.956, 120);
    sunAssertNoonNear(sun.noon, 761, "Tromso midnight sun starts +1");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_UP_ALL_DAY);
    Test.assert(sun.rise == null && sun.set == null);
    Test.assert(sun.civilBegin == null);
    Test.assert(sun.civilEnd == null);
    return true;
}

(:test)
function sunReferenceTromsoEquinox(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 9, 23, 69.6496, 18.956, 120);
    sunAssertNoonNear(sun.noon, 757, "Tromso equinox");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 388, "Tromso equinox rise");
    sunAssertNear(sun.set, 1123, "Tromso equinox set");
    sunAssertNear(sun.civilBegin, 327, "Tromso equinox civilBegin");
    sunAssertNear(sun.civilEnd, 1183, "Tromso equinox civilEnd");
    return true;
}

(:test)
function sunReferenceUshuaia(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 12, 21, -54.8, -68.3, -180);
    sunAssertNoonNear(sun.noon, 811, "Ushuaia");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 291, "Ushuaia rise");
    sunAssertNear(sun.set, 1331, "Ushuaia set");
    sunAssertNear(sun.civilBegin, 234, "Ushuaia civilBegin");
    sunAssertNear(sun.civilEnd, 1389, "Ushuaia civilEnd");
    return true;
}

(:test)
function sunReferenceSingaporeEquator(logger as Test.Logger) as Boolean {
    var sun = TwoSunsSun.compute(2026, 3, 20, 1.35, 103.82, 480);
    sunAssertNoonNear(sun.noon, 792, "Singapore equator");
    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);
    sunAssertNear(sun.rise, 429, "Singapore equator rise");
    sunAssertNear(sun.set, 1155, "Singapore equator set");
    sunAssertNear(sun.civilBegin, 408, "Singapore equator civilBegin");
    sunAssertNear(sun.civilEnd, 1176, "Singapore equator civilEnd");
    return true;
}
