#!/usr/bin/env python3
"""Generate source/test/TwoSunsSunReferenceTest.mc from the US Naval Observatory reference table.

The table is research_notes/Body Battery and sun face research/reference_sun_times.tsv (27 place-and-date
cases, USNO times in the local zone; SUN_TSV overrides the path). One test per row; tolerance 2 minutes. Rows with no USNO event assert "no event"; the two polar-transition days assert nothing stricter
than the solar noon (docs/spec.md: +-1 day accepted at the polar-circle transitions).

Run:  python3 tools/gen_sun_tests.py
"""
import csv
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TSV = Path(os.environ.get("SUN_TSV", ROOT.parent / "research_notes" / "Body Battery and sun face research" / "reference_sun_times.tsv"))
OUT = ROOT / "source" / "test" / "TwoSunsSunReferenceTest.mc"


def minutes(text):
    if not text or text == "--":
        return None
    h, m = text.split(":")
    return int(h) * 60 + int(m)


def ident(name):
    return re.sub(r"[^A-Za-z0-9]+", " ", name).title().replace(" ", "")


def float_lit(value):
    text = repr(float(value))
    return text


rows = list(csv.DictReader(TSV.open(), delimiter="\t"))
lines = [
    "import Toybox.Lang;",
    "import Toybox.Test;",
    "",
    "// GENERATED by tools/gen_sun_tests.py from reference_sun_times.tsv (US Naval Observatory). Do not edit by hand.",
    "// Every value is local minutes since local midnight; tolerance is 2 minutes (a sunset after midnight is +1440).",
    "// Pro only: TwoSunsSun is compiled into the Pro build alone (docs/decisions.md ADR-020, Free + Pro ladder), so every test is (:test, :pro).",
    "",
    "(:debug)",
    "function sunAssertNear(actual as Number or Null, expected as Number, label as String) as Void {",
    "    Test.assert(actual != null);",
    "    Test.assertMessage((actual as Number) - expected <= 2 && expected - (actual as Number) <= 2, label + \" \" + actual + \" vs \" + expected);",
    "}",
    "",
    "(:debug)",
    "function sunAssertNoonNear(actual as Number, expected as Number, label as String) as Void {",
    "    // Solar noon is compared around the clock (a noon just after midnight would be 1440 + n).",
    "    var diff = (actual - expected) % TwoSunsConfig.MINUTES_PER_DAY;",
    "    if (diff < 0) {",
    "        diff += TwoSunsConfig.MINUTES_PER_DAY;",
    "    }",
    "    Test.assertMessage(diff <= 2 || diff >= TwoSunsConfig.MINUTES_PER_DAY - 2, label + \" noon \" + actual + \" vs \" + expected);",
    "}",
    "",
]
seen = set()
for row in rows:
    name = ident(row["place"])
    assert name not in seen, name
    seen.add(name)
    y, m, d = (int(x) for x in row["local_date"].split("-"))
    offset = round(float(row["local_utc_offset_h"]) * 60)
    rise, sett, noon = minutes(row["usno_rise"]), minutes(row["usno_set"]), minutes(row["usno_solar_noon"])
    cb, ce = minutes(row["usno_civil_begin"]), minutes(row["usno_civil_end"])
    note = row["note"]
    transition = "transition day" in note
    if rise is not None and sett is not None and sett < rise:
        sett += 1440   # sunset after local midnight
    lines += ["(:test, :pro)", f"function sunReference{name}(logger as Test.Logger) as Boolean {{",
              f"    var sun = TwoSunsSun.compute({y}, {m}, {d}, {float_lit(row['lat'])}, {float_lit(row['lon'])}, {offset});"]
    if noon is not None:   # USNO has no transit on a polar-night day
        lines.append(f"    sunAssertNoonNear(sun.noon, {noon}, \"{row['place']}\");")
    if transition:
        lines.append("    // Transition day: USNO lists events one noon-declination says do not exist; nothing stricter than noon.")
    elif rise is None and sett is None:
        # polar: the row's noon-only USNO data; the kind says which way
        kind = "SUN_UP_ALL_DAY" if "midnight sun" in row["place"].lower() else "SUN_DOWN_ALL_DAY"
        lines += [f"    Test.assertEqual(sun.kind, TwoSunsConfig.{kind});",
                  "    Test.assert(sun.rise == null && sun.set == null);"]
    else:
        lines += ["    Test.assertEqual(sun.kind, TwoSunsConfig.SUN_NORMAL);",
                  f"    sunAssertNear(sun.rise, {rise}, \"{row['place']} rise\");",
                  f"    sunAssertNear(sun.set, {sett}, \"{row['place']} set\");"]
    if not transition:
        for field, value in (("civilBegin", cb), ("civilEnd", ce)):
            if value is None:
                lines.append(f"    Test.assert(sun.{field} == null);")
            else:
                lines.append(f"    sunAssertNear(sun.{field}, {value}, \"{row['place']} {field}\");")
    lines += ["    return true;", "}", ""]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} tests")
